NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.tj-se.smartsign.app-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.tj-se.smartsign.app-cert.pem
    OrganizationalUnitIdentifier: peer
